### ISSUE TITLE
RDM oled patch failed with Volumio 3.449

### ISSUE THREAD

**Issue by HiroyukiHirohata** [audiophonics/RaspDacMini#8]
RDM Oled patch failed with Volumio 3.449
This patch also failed with MoOde 8.3.0
Here's the service state.
Don't know but seeing nodejs version incompatibilities??

Volumio@volumio:~$ sudo systemctl status oled
● oled.service - OLED Display Service
   Loaded: loaded (/etc/systemd/system/oled.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2023-04-13 18:34:27 JST; 1h 49min ago
  Process: 863 ExecStart=/usr/bin/sudo /usr/bin/node /usr/local/etc/raspdacminioled/index.js volumio (code=exited, status=1/FAILURE)
 Main PID: 863 (code=exited, status=1/FAILURE)

Apr 13 18:34:26 volumio systemd[1]: Started OLED Display Service.
Apr 13 18:34:27 volumio sudo[863]:     root : TTY=unknown ; PWD=/usr/local/etc/raspdacminioled ; USER=root ; COMMAND=/usr/bin/node /usr/local/etc/raspdacminioled/index.js volumio
Apr 13 18:34:27 volumio sudo[863]: pam_unix(sudo:session): session opened for user root by (uid=0)
Apr 13 18:34:27 volumio sudo[863]: pam_unix(sudo:session): session closed for user root
Apr 13 18:34:27 volumio systemd[1]: oled.service: Main process exited, code=exited, status=1/FAILURE
Apr 13 18:34:27 volumio systemd[1]: oled.service: Failed with result 'exit-code'.

**Comment by audiophonics** [comment]
I just tried Volumio 3.449 on a RPI 4 rev 1.5+ and also on a RPI 3 rev 1.2. 

Both were running fine, so I suspect it is neither hardware-related nor an issue with nodejs but rather something in my base code. 

Could you please stop the service and run the software manually so we can get more detailed logs ? 

```
systemctl stop oled
cd /usr/local/etc/raspdacminioled 
sudo node index.js volumio
```

Also do you see the logo appearing at all or does the display remain dark the whole time ?

**Comment by HiroyukiHirohata** [comment]
thx, LCD keeps blank
and here"s the output

olumio@volumio:~$ sudo systemctl stop oled
volumio@volumio:~$ 
volumio@volumio:~$ cd /usr/local/etc/raspdacminioled/
volumio@volumio:/usr/local/etc/raspdacminioled$ 
volumio@volumio:/usr/local/etc/raspdacminioled$ sudo node index.js volumio
/usr/local/etc/raspdacminioled/node_modules/ssd1306/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/etc/raspdacminioled/node_modules/ssd1306/node_modules/rpio/build/rpio.node
 → /usr/local/etc/raspdacminioled/node_modules/ssd1306/node_modules/rpio/build/Debug/rpio.node
 → /usr/local/etc/raspdacminioled/node_modules/ssd1306/node_modules/rpio/build/Release/rpio.node
 → /usr/local/etc/raspdacminioled/node_modules/ssd1306/node_modules/rpio/out/Debug/rpio.node
 → /usr/local/etc/raspdacminioled/node_modules/ssd1306/node_modules/rpio/Debug/rpio.node
 → /usr/local/etc/raspdacminioled/node_modules/ssd1306/node_modules/rpio/out/Release/rpio.node
 → /usr/local/etc/raspdacminioled/node_modules/ssd1306/node_modules/rpio/Release/rpio.node
 → /usr/local/etc/raspdacminioled/node_modules/ssd1306/node_modules/rpio/build/default/rpio.node
 → /usr/local/etc/raspdacminioled/node_modules/ssd1306/node_modules/rpio/compiled/14.15.4/linux/arm/rpio.node
 → /usr/local/etc/raspdacminioled/node_modules/ssd1306/node_modules/rpio/addon-build/release/install-root/rpio.node
 → /usr/local/etc/raspdacminioled/node_modules/ssd1306/node_modules/rpio/addon-build/debug/install-root/rpio.node
 → /usr/local/etc/raspdacminioled/node_modules/ssd1306/node_modules/rpio/addon-build/default/install-root/rpio.node
 → /usr/local/etc/raspdacminioled/node_modules/ssd1306/node_modules/rpio/lib/binding/node-v83-linux-arm/rpio.node
    at bindings (/usr/local/etc/raspdacminioled/node_modules/ssd1306/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/usr/local/etc/raspdacminioled/node_modules/ssd1306/node_modules/rpio/lib/rpio.js:17:34)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/etc/raspdacminioled/node_modules/ssd1306/SSD1306.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  tries: [
    '/usr/local/etc/raspdacminioled/node_modules/ssd1306/node_modules/rpio/build/rpio.node',
    '/usr/local/etc/raspdacminioled/node_modules/ssd1306/node_modules/rpio/build/Debug/rpio.node',
    '/usr/local/etc/raspdacminioled/node_modules/ssd1306/node_modules/rpio/build/Release/rpio.node',
    '/usr/local/etc/raspdacminioled/node_modules/ssd1306/node_modules/rpio/out/Debug/rpio.node',
    '/usr/local/etc/raspdacminioled/node_modules/ssd1306/node_modules/rpio/Debug/rpio.node',
    '/usr/local/etc/raspdacminioled/node_modules/ssd1306/node_modules/rpio/out/Release/rpio.node',
    '/usr/local/etc/raspdacminioled/node_modules/ssd1306/node_modules/rpio/Release/rpio.node',
    '/usr/local/etc/raspdacminioled/node_modules/ssd1306/node_modules/rpio/build/default/rpio.node',
    '/usr/local/etc/raspdacminioled/node_modules/ssd1306/node_modules/rpio/compiled/14.15.4/linux/arm/rpio.node',
    '/usr/local/etc/raspdacminioled/node_modules/ssd1306/node_modules/rpio/addon-build/release/install-root/rpio.node',
    '/usr/local/etc/raspdacminioled/node_modules/ssd1306/node_modules/rpio/addon-build/debug/install-root/rpio.node',
    '/usr/local/etc/raspdacminioled/node_modules/ssd1306/node_modules/rpio/addon-build/default/install-root/rpio.node',
    '/usr/local/etc/raspdacminioled/node_modules/ssd1306/node_modules/rpio/lib/binding/node-v83-linux-arm/rpio.node'
  ]
}
volumio@volumio:/usr/local/etc/raspdacminioled$

**Comment by audiophonics** [comment]
The software is complaining about a dependency missing. That one is supposed to be built and bundled during the patch construction. 
That should be an easy fix but I have a couple more questions before I can provide a solution if you do not mind. 

_(I am assuming you are still trying the install on Volumio but I can provide the equivalent set of instructions for moOde if you prefer)._



- First : did you built the whole patch yourself with [those instructions](https://github.com/audiophonics/RaspDacMini/tree/v2.1) or did you use my [prebuilt patch from here](https://github.com/audiophonics/RaspDacMini/tree/volumio) ? 

- It would help to see what has actually made its way into the final install directory, this should tell us enough : 
`find /usr/local/etc/raspdacminioled/ -maxdepth 2`

- Finally it doesn't hurt to have your system / hardware version with : 
`cat /proc/cpuinfo`
`uname -a`
